implement infra config and migrations

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,6 +13,7 @@ commands:
             # Your code here
             aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID}
             aws cloudformation delete-stack --stack-name udapeople-frontend-${CIRCLE_WORKFLOW_ID}
+            exit 1
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
@@ -24,12 +25,14 @@ commands:
           # Add when this will run
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
+            SUCCESS=$(curl -H "token: 33ad81a5-9ea1-40d8-914f-e81150bad3f7" --request GET https://api.memstash.io/values/${migration_${CIRCLE_WORKFLOW_ID:0:7})
+
             if(( $SUCCESS==1 )); 
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
+              cd ~/backend
+              npm install
+              #  Add revert code here. You can find this in the Getting Started section.
+              npm run migrations:revert
               exit 1
             fi
             
@@ -170,7 +173,7 @@ jobs:
       - persist_to_workspace:
           root: ~/
           paths:
-            - project/.circleci/ansible/inventory.txt
+            - .circleci/ansible/inventory.txt
       - destroy-environment
 
   configure-infrastructure:
@@ -178,36 +181,51 @@ jobs:
       - image: python:3.7-alpine3.11
     steps:
       # Checkout code from git
+      - checkout
       # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          fingerprints: ["87:15:d0:14:78:d1:dc:e9:8c:25:5f:d4:ef:2b:3b:98"]
       # attach workspace
+      - attach_workspace:
+          at: ~/
       - run:
           name: Install dependencies
           command: |
-            # Your code here
-            exit 1
+            apk add --update ansible
       - run:
           name: Configure server
           command: |
             # Your code here
-            exit 1
-      # Here's where you will add some code to rollback on failure      
+            ansible-playbook -i .circleci/ansible/inventory.txt ./circleci/ansible/configure-server.yml
+      - destroy-environment
 
   run-migrations:
     docker:
       - image: circleci/node:13.8.0
     steps:
       # Checkout code from git
+      - checkout
       - run:
           name: Run migrations
           command: |
             # Your code here
-            exit 1
+            cd backend
+            npm install
+            # Core assumption is that we can read ths file in the next job
+            npm run migrations >> ./migration_output.txt
       - run:
           name: Send migration results to memstash
           command: |
             # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
+            OUTPUT=$(cat ./migration_output.txt)
+            SUCCESS=0
+            if [[ $OUTPUT == *"has been executed successfully"* ]]; then
+              SUCCESS=1
+            fi
+            curl -H "Content-Type: text/plain" -H "token: 33ad81a5-9ea1-40d8-914f-e81150bad3f7" --request PUT --data "$SUCCESS" https://api.memstash.io/values/${migration_${CIRCLE_WORKFLOW_ID:0:7}
+      # Here's where you will add some code to rollback on failure   
+      - revert-migrations
+      - destroy-environment
 
   deploy-frontend:
     docker:
